version: '2.1'

services:
  ldap-server:
    image: ldap-server
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 1389:1389
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 server.js